name: bestow_app_api_riverpod
description: Riverpod bindings for bestow_app_api
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
